### PR TITLE
fix: IMU get sensor readings return values closes #130

### LINKED ISSUE #130: fix: IMU get sensor readings return values
Functions have pointless return values.  Resolve so that return values propagate failures.

### PR DESCRIPTION
**Pull request by atharvakedia**

### CODE REVIEW

**Comment by ntlhui** [comment]
Is this ready for review?

File: src/imu/imu.cpp
Comment (ntlhui) [inline src/imu/imu.cpp:1]: Repeat for Gryroscope and mag

**Review by ntlhui — CHANGES_REQUESTED** [review]

File: src/imu/imu.cpp [hunk 1]
```diff
@@ -53,6 +53,15 @@ void setupICM(void)
 bool getAccelerometer(float *acc_x, float *acc_y, float *acc_z)
 {
 #if SF_PLATFORM == SF_PLATFORM_PARTICLE
+
+    myICM.getAGMT();
+
+    if (myICM.status != ICM_20948_Stat_Ok)
+    {
+        SF_OSAL_printf("Failed to get accelerometer data");
```
Comment (ntlhui) [inline src/imu/imu.cpp:61]: Don't use printf, add to FLOG

**Review by ntlhui — CHANGES_REQUESTED** [review]

File: src/imu/imu.cpp [hunk 2]
```diff
@@ -53,6 +53,14 @@ void setupICM(void)
...
 #if SF_PLATFORM == SF_PLATFORM_PARTICLE
+
+    myICM.getAGMT();
+
+    if (myICM.status != ICM_20948_Stat_Ok)
+    {
+        FLOG_AddError(FLOG_ICM_FAIL, 0);
+        return false;
+    }
     ICM_20948_AGMT_t agmt = myICM.getAGMT();
```
Comment (ntlhui) [inline src/imu/imu.cpp:64]: Lines 57 and 64 appear to have duplicate behavior.  Would it be simpler to move line 64 earlier?

File: src/imu/imu.cpp [hunk 3]
```diff
@@ -65,6 +73,14 @@ bool getAccelerometer(float *acc_x, float *acc_y, float *acc_z)
...
```
Comment (ntlhui) [inline src/imu/imu.cpp:84]: Lines 77 and 84 appear to have duplicate behavior.  Would it be simpler to move line 84 earlier?

File: src/imu/imu.cpp [hunk 4]
```diff
@@ -77,6 +93,14 @@ bool getGyroscope(float *gyr_x, float *gyr_y, float *gyr_z)
...
```
Comment (ntlhui) [inline src/imu/imu.cpp:104]: Lines 97 and 104 appear to have duplicate behavior.  Would it be simpler to move line 104 earlier?

**Comment by atharvakedia** [comment]
Yes, I see the redundancy. Fixed

File: src/imu/imu.cpp [hunk 5]
```diff
@@ -53,8 +53,14 @@ void setupICM(void)
...
 #if SF_PLATFORM == SF_PLATFORM_PARTICLE
-    ICM_20948_AGMT_t agmt = myICM.getAGMT();
+    myICM.getAGMT();
 
+    if (myICM.status != ICM_20948_Stat_Ok)
+    {
+        FLOG_AddError(FLOG_ICM_FAIL, 0);
+        return false;
+    }
+    ICM_20948_AGMT_t agmt = myICM.agmt;
```
Comment (ntlhui) [inline src/imu/imu.cpp:63]: Would it not be simpler to do this:
```
ICM_20948_AGMT_t agmt = myICM.getAGMT();

if(myICM.status != ICM_20948_Stat_Ok)
{
    FLOG_AddError(FLOG_ICM_FAIL, 0);
    return false;
}
```

File: src/imu/imu.cpp [hunk 6]
```diff
@@ -65,7 +71,14 @@ bool getAccelerometer(float *acc_x, float *acc_y, float *acc_z)
...
 #if SF_PLATFORM == SF_PLATFORM_PARTICLE
-    ICM_20948_AGMT_t agmt = myICM.getAGMT();
+    myICM.getAGMT();
+
+    if (myICM.status != ICM_20948_Stat_Ok)
+    {
+        FLOG_AddError(FLOG_ICM_FAIL, 0);
+        return false;
+    }
+    ICM_20948_AGMT_t agmt = myICM.agmt;
```
Comment (ntlhui) [inline src/imu/imu.cpp:81]: Would it not be simpler to do this:
```
ICM_20948_AGMT_t agmt = myICM.getAGMT();

if(myICM.status != ICM_20948_Stat_Ok)
{
    FLOG_AddError(FLOG_ICM_FAIL, 0);
    return false;
}
```

File: src/imu/imu.cpp [hunk 7]
```diff
@@ -77,7 +90,14 @@ bool getGyroscope(float *gyr_x, float *gyr_y, float *gyr_z)
...
```
Comment (ntlhui) [inline src/imu/imu.cpp:100]: Would it not be simpler to do this:
```
ICM_20948_AGMT_t agmt = myICM.getAGMT();

if(myICM.status != ICM_20948_Stat_Ok)
{
    FLOG_AddError(FLOG_ICM_FAIL, 0);
    return false;
}
```

**Review by ntlhui — CHANGES_REQUESTED** [review]

File: src/imu/imu.cpp (hunk 7 above)
Comment (atharvakedia) [reply src/imu/imu.cpp]: Yes! thank you for the feedback. Changes have been made.

Comment (ntlhui) [reply src/imu/imu.cpp]: If this is now ready for review, please re-request review on this

**Comment by ntlhui** [comment]
If this is ready for my review, please re-request review by clicking the refresh circle
image

File: src/imu/imu.cpp
Comment (ntlhui) [inline src/imu/imu.cpp:1]: Should the same be done for getTemperature?

**Review by ntlhui — CHANGES_REQUESTED** [review]

File: src/imu/imu.cpp
Comment (atharvakedia) [reply src/imu/imu.cpp:1]: Yes, done!

**Review by ntlhui — APPROVED** [review]
