### PR TITLE
Include DEL (127 in ASCII) input to be recognized as backspace

### LINKED ISSUE #173: CLI Backspace for PC Build
**Describe the bug**
For MacOS users, the "backspace" button is mapped to DEL, which is 127 in the ASCII table.
My MacOS is Sequoia (Version 15.0) and runs on an Intel Core i7.

**To Reproduce**
1. Build the ```smartfin_pc``` build
2. ```Run build/pc_hal/smartfin_pc```
3. Enter ```#CLI``` without a trailing newline
4. Press backspace/delete
5. See error

**Expected behavior**
Backspace in the command line

**Screenshots**

**Hardware Configuration(please complete the following information):**
 - Hardware Version [PCB revision]: Docker Build
 - Potted [Y/n]: n
 - Firmware Version: 94bb762

### PR DESCRIPTION
**Pull request by ezh247467**
Fixes #173 by recognizing DEL input as backspace.

### CODE REVIEW

File: src/cli/conio.cpp [hunk 1]
```diff
@@ -127,6 +127,7 @@ extern "C"
                 userInput = SF_OSAL_getch();
                 switch (userInput)
                 {
+                case 127:
```
Comment (ntlhui) [inline src/cli/conio.cpp:130]: This maybe should be wrapped in the `SMARTFIN_PLATFORM` preprocessor guard, as it is behavior specific to the PC build.

**Review by ntlhui — CHANGES_REQUESTED** [review]

File: src/cli/conio.cpp (hunk 1 above)
Comment (ezh247467) [reply src/cli/conio.cpp:130]: This part of the code should already be part of the glibc preprocessor guard.

**Review by ntlhui — APPROVED** [review]

**Comment by ntlhui** [comment]
@ezh247467 Please remember to use Conventional Commit style: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ezh247467** [comment]
For future reference, if the issue I'm working on requires multiple commits due to the scale, do I still put 'fix:' as the prefix for each commit even though individually they did not yet completely fix the issue?

**Comment by ntlhui** [comment]
Yes if the changes are related to correcting code behavior.
